# Generated by Django 6.0.3 on 2026-03-30 17:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
